### PR TITLE
Add twitter-text & support Heroku

### PR DESCRIPTION
**Pull request by Mikaleb**
This PR mostly adds Twitter-text to check the length of the content of the tweet (they have a whole system of weight and not counting an utf special char as 2 (like ñ for ex).

I also add some support for deploying on Heroku (free, easy to deploy)

### CODE REVIEW

**Comment by Mikaleb** [comment]
I shall squash my commits next time

**Comment by plhery** [comment]
Why did you add tsnode and tsconfig-paths? the js is supposed to be built?

Why did you add an express server? (I don't want the whole thing to be an "usine à gaz", plus I hate dependencies because it potentially creates security issues and you have to upgrade them regularly)

**Comment by Mikaleb** [comment]
tsnode and tsconfig-path : to use the paths of tsconfig.json, they are not interpreted correctly if you use '~/chronobot' for example.
Didn't found better for now, I'm a regular user of nuxt which handles theses things natively ;)

For express, it's a robust option to deploy the project on any kind of platform (like Heroku, but it can be github pages, cloudflare, etc) that need a port handling natively.

**Comment by Mikescops** [comment]
Hello,

I don't see how you can run such process with a static file hosting like Github Pages. But let say you want to run it on Heroku and you're forced to open a port. Don't use express, which is a bloatware for such use. If you simply require `http` native package you can open a HTTP port which is what you want.

Concerning ts-node, it my be great to run one time script or debug a ts code on the fly but it's not recommended for production nor development. You have everything within default tsc compiler:

- `--watch` : to keep an eye on your files tree and rebuild your project upon changes
- `--project tsconfig.prod.json` to choose your compiler settings

And many more [here](https://www.typescriptlang.org/docs/handbook/compiler-options.html).

When you jump in any project, whether it's for work or side-projects, try to minimize the changes per PRs and follow the current stack.
Example, using yarn when npm is currently in use could be avoided, or proposed in a dedicated PR. Same thing for removing some parameters in tsconfig.

With the current title you can then split into 2 dedicated PRs:
- one for twitter-text
- one for Heroku support

- (+) one for each extra idea mentioned previously

That way you're assured that part of your ideas are added to the repository and not blocking others.

Hope this comment can help you for your next contributions here and there. Let me know if you have remarks or questions :smile:

**Comment by Mikaleb** [comment]
Neat ! Didn't knew about it, will do, thanks a lot.

**Comment by Mikaleb** [comment]
Note : I'll remove everything for Heroku, their free tier can't keep the process idle without shutting down.

**Comment by plhery** [comment]
I'll fix the length issue without the need for a heavy dependency :) but thx for making me realize the issue!

- emojis count as 1 chars -> [...message].length will give the right number
- the links count as 23 chars -> a simple substraction will do

**Comment by plhery** [comment]
For Heroku, indeed, I don't want to make the whole thing more complex just for it, but you can create a "heroku" fork and we can link it in the readme

**Pull request closed without merging**
